title: Ahmed A. Alhofy
logo: /assets/img/AA.png
# description: Aspiring Data Scientist | BSc Student in Information Systems, Faculty of Computers and Artificial Intelligence, University of Sadat City
# show_downloads: true
theme: jekyll-theme-minimal
