title: Ahmed Ayman
logo: /assets/img/Me2.jpg
# description: Aspiring Data Scientist | BSc Student in Information Systems, Faculty of Computers and Artificial Intelligence, University of Sadat City
# show_downloads: true
theme: jekyll-theme-minimal
